#!/usr/bin/env python3
"""
Build packages/ui/src/data/gazetteer.ts from the GeoNames dump (CC BY 4.0).

  python3 packages/ui/scripts/build-gazetteer.py <dir with cities5000.txt, admin1CodesASCII.txt, countryInfo.txt>

Ships every place with 15,000+ people, every first-level region, and every
country, so a name from any real dataset lands somewhere: the city if we
know it, the region if we know that, the country at worst.
"""
import json, re, sys, unicodedata, collections
src = sys.argv[1]
MIN_POP = 15000
ASCII = re.compile(r"^[A-Za-z\u00C0-\u017F .'\-]+$")  # Latin script, diacritics allowed; normalised later

def norm(s):
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode()
    return re.sub(r"[^a-z0-9]+", " ", s.lower()).strip()

countries = {}
for line in open(f"{src}/countryInfo.txt", encoding="utf-8"):
    if line.startswith("#"): continue
    p = line.rstrip("\n").split("\t")
    countries[p[0]] = {"iso": p[0], "iso3": p[1], "name": p[4], "capital": p[5]}

admin1 = {}
for line in open(f"{src}/admin1CodesASCII.txt", encoding="utf-8"):
    code, name, ascii_name, _ = line.rstrip("\n").split("\t")
    admin1[code] = {"code": code, "name": ascii_name}

cities = []
csum = collections.defaultdict(lambda: [0.0, 0.0, 0])   # country -> [lat*pop, lon*pop, pop]
asum = collections.defaultdict(lambda: [0.0, 0.0, 0])   # admin1 code -> same
for line in open(f"{src}/cities5000.txt", encoding="utf-8"):
    p = line.rstrip("\n").split("\t")
    name, ascii_name, alts, lat, lon, cc, a1, pop = p[1], p[2], p[3], float(p[4]), float(p[5]), p[8], p[10], int(p[14] or 0)
    w = max(pop, 1)
    csum[cc][0] += lat * w; csum[cc][1] += lon * w; csum[cc][2] += w
    key = f"{cc}.{a1}"
    asum[key][0] += lat * w; asum[key][1] += lon * w; asum[key][2] += w
    if pop < MIN_POP: continue
    # The native spelling always rides along (Muenchen/München → Munich), then
    # the Latin-script alternates, shortest first so "New York" beats
    # "New York City Area" and stays inside the cap.
    aliases = []
    seen = {norm(ascii_name)}
    if norm(name) not in seen and norm(name):
        seen.add(norm(name)); aliases.append(name)
    if pop >= 50000:
        cap = 12 if pop >= 500000 else 6
        # Real alternate spellings start with a capital, contain a vowel and
        # usually share the first letter ("Muenchen", "München"); transliteration
        # keys like "mwnkh" do not, and they were crowding the real ones out.
        first = norm(ascii_name)[:1]
        def real(a):
            n = norm(a)
            return ASCII.match(a) and len(a) >= 4 and a[0].isupper() and any(v in n for v in "aeiouy")
        cands = [a for a in alts.split(",") if real(a)]
        cands.sort(key=lambda a: (0 if norm(a)[:1] == first else 1, len(a)))
        for a in cands:
            if norm(a) not in seen:
                seen.add(norm(a)); aliases.append(a)
            if len(aliases) >= cap: break
    cities.append([ascii_name, cc, a1, round(lat, 3), round(lon, 3), pop, aliases])

cities.sort(key=lambda c: -c[5])
regions = []
for code, a in admin1.items():
    s = asum.get(code)
    if not s or s[2] == 0: continue
    cc = code.split(".")[0]
    regions.append([a["name"], cc, code.split(".")[1], round(s[0] / s[2], 3), round(s[1] / s[2], 3)])
ctry = []
for iso, c in countries.items():
    s = csum.get(iso)
    if not s or s[2] == 0: continue
    ctry.append([c["name"], iso, c["iso3"], round(s[0] / s[2], 3), round(s[1] / s[2], 3)])

out = f"""/* eslint-disable */
/**
 * Offline gazetteer. Generated by scripts/build-gazetteer.py — do not edit.
 *
 * Source: GeoNames (https://www.geonames.org), Creative Commons Attribution
 * 4.0. Cities of 15,000+ people, first-level regions and countries, with
 * region and country positions as population-weighted centres of their cities.
 *
 * Rows: CITIES [asciiName, countryIso2, admin1Code, lat, lon, population, aliases]
 *       REGIONS [name, countryIso2, admin1Code, lat, lon]
 *       COUNTRIES [name, iso2, iso3, lat, lon]
 */
export const CITIES: [string, string, string, number, number, number, string[]][] = {json.dumps(cities, ensure_ascii=True, separators=(",", ":"))};
export const REGIONS: [string, string, string, number, number][] = {json.dumps(regions, ensure_ascii=True, separators=(",", ":"))};
export const COUNTRIES: [string, string, string, number, number][] = {json.dumps(ctry, ensure_ascii=True, separators=(",", ":"))};
"""
open("packages/ui/src/data/gazetteer.ts", "w").write(out)
print(f"cities {len(cities)}  regions {len(regions)}  countries {len(ctry)}  bytes {len(out):,}")
