#!/usr/bin/env node
/**
 * Make a theme from one brand colour.
 *
 *   node packages/ui/scripts/make-theme.mjs --name pfizer --primary "#0000C9" [--label "Pfizer blue"]
 *
 * Derives the dark ink, the selection tint, the focus ring and the rank bands
 * from the primary, checks the primary can carry white text, and writes
 * packages/ui/src/themes/<name>.ts plus a registration line in themes.ts.
 * Nothing else in the system changes — neutrals, status colours and the chart
 * series are shared by every theme on purpose.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const args = Object.fromEntries(
  process.argv.slice(2).reduce((acc, a, i, arr) => {
    if (a.startsWith("--")) acc.push([a.slice(2), arr[i + 1]]);
    return acc;
  }, []),
);
if (!args.name || !args.primary) {
  console.error('usage: make-theme --name <slug> --primary "#RRGGBB" [--label "Shown in the picker"]');
  process.exit(1);
}
const name = args.name.toLowerCase().replace(/[^a-z0-9]+/g, "-");
const label = args.label ?? name[0].toUpperCase() + name.slice(1);

/* colour maths --------------------------------------------------------- */
const hexToRgb = (h) => [0, 2, 4].map((i) => parseInt(h.replace("#", "").slice(i, i + 2), 16));
const rgbToHex = (r) => "#" + r.map((v) => Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, "0")).join("").toUpperCase();
const mix = (a, b, t) => a.map((v, i) => v + (b[i] - v) * t);
const lum = ([r, g, b]) => {
  const f = (c) => { c /= 255; return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4; };
  return 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b);
};
const contrastWithWhite = (rgb) => (1.05) / (lum(rgb) + 0.05);

const primary = hexToRgb(args.primary);
const white = [255, 255, 255], black = [0, 0, 0];
const contrast = contrastWithWhite(primary);
if (contrast < 4.5) {
  console.error(`The primary ${args.primary} only reaches ${contrast.toFixed(1)}:1 against white text (needs 4.5). Pick a darker shade of the brand for the primary; the light one can be the rank-2 band.`);
  process.exit(2);
}
const colors = {
  primary: rgbToHex(primary),
  secondary: rgbToHex(mix(primary, black, 0.55)),
  selected: rgbToHex(mix(primary, white, 0.9)),
  borderFocus: rgbToHex(mix(primary, white, 0.25)),
  info: rgbToHex(mix(primary, white, 0.25)),
  rank1: rgbToHex(primary),
  rank2: rgbToHex(mix(primary, white, 0.35)),
};

/* write ------------------------------------------------------------------ */
const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, "..", "src");
const dir = join(src, "themes");
mkdirSync(dir, { recursive: true });
const file = join(dir, `${name}.ts`);
writeFileSync(file, `import type { Theme } from "../themes";

/** Generated by scripts/make-theme.mjs from ${args.primary}. Edit freely. */
export const ${name.replace(/-/g, "_").toUpperCase()}: Theme = {
  name: "${name}",
  label: ${JSON.stringify(label)},
  note: "Made from ${args.primary}. White text on the primary reads at ${contrast.toFixed(1)}:1.",
  colors: ${JSON.stringify(colors, null, 4).replace(/"([a-zA-Z0-9]+)":/g, "$1:").replace(/\n/g, "\n  ")},
};
`);

const themesTs = join(src, "themes.ts");
let t = readFileSync(themesTs, "utf8");
const constName = name.replace(/-/g, "_").toUpperCase();
if (!t.includes(`./themes/${name}`)) {
  t = t.replace(
    /export const THEMES: Record<string, Theme> = \{([^}]*)\};/,
    (m, inner) => `export const THEMES: Record<string, Theme> = {${inner.trimEnd()}, ${name}: ${constName} };`,
  );
  t = `import { ${constName} } from "./themes/${name}";\n` + t;
  writeFileSync(themesTs, t);
}
console.log(`Wrote ${file} and registered "${name}" in THEMES.`);
console.log(`Use it with <ThemeProvider theme="${name}"> or set "theme": "${name}" in factory.config.json.`);
console.log(`Primary ${colors.primary} · ink ${colors.secondary} · tint ${colors.selected} · white-text contrast ${contrast.toFixed(1)}:1`);
